### ISSUE TITLE
Who pushed Node modules

### ISSUE THREAD

**Issue by swadhinroutray** [Privacy-Engineering-CMU/retired-Privacy-Engineering-cmu.github.io#1]
Guys, who pushed node modules? Can we please get rid of it.

**Comment by yashmaurya01** [comment]
🌟 Hey there! 🌟

First off, a massive shoutout to you for keeping an eagle eye on our repository! 🦅 Your diligence is the superhero cape that keeps our codebase flying high and bug-free. 🚀

Now, onto the matter at hand: 🧐 Node Modules Invasion? Fear not, for our digital fortress stands unbreached! After donning our detective hats 🕵️‍♂️ and combing through the repository with the precision of a laser-guided comb, we've confirmed that no node modules have snuck past our gates.

Could it be a phantom menace? 🌌 Perhaps the shadows you're seeing are cast by the lingering specters of a bygone branch or the mischievous sprites of local environment settings. 🧙‍♂️

Here’s a spell to banish these apparitions:

Sync with the Sacred Main Branch: Pull the latest changes to ensure you're not in a timeline that's diverged from our reality.
Purge the Shadows: Double-check your local setup to make sure it’s not harboring any unwanted stowaways.
Still haunted? 👻 We’re here for you! Shoot us a message, drop us a line, send a raven – whatever works. Your feedback isn’t just appreciated, it’s the cornerstone of our community castle.

Together, we shall keep our code kingdom prosperous and dragon-free! 🐉

Stay awesome,
MSIT-PE GitHub Team
